---
- hosts: localhost
  tasks:
  - name: Create a ticket in SNOW updated
    register: new_change_request
    snow_record:
      data:
        assignment_group: Application Development
        category: Software
        short_description: 'change 11/11/2020'
        start_date: '2020-11-11 00:00:00'
        type: Normal
      instance: dev95751
      password: 123@Aanah
      state: present
      table: change_request
      username: admin
    register: new_change_request
  - debug: var=new_change_request.record.number
